
		<p>These pages are designed to demonstrate a rendering problem that can happen if you
		are a dunderheaded n00b who doesn't understand MIME types. Basically, the CSS on these
		pages is dynamic, created by PHP code. If you don't tell the browser it is receiving
		CSS then it could misinterpret what you send it. In empirical tests, only Firefox and
		Webkit actually seemed to exhibit this behaviour - other browsers interpret the
		results as CSS anyway, based on some kind of built-in (non-standard) smarts.</p>

		<p>Please <a href="http://twitter.com/dominicsayers">tweet me</a> (@dominicsayers) if you want more details.</p>